version: "3.8"

services:
  flower-shop-db:
    image: mysql:8.0.3
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=SAstudent1
    ports:
      - 3366:3306