name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      flower-shop-test:
        image: mysql:8.0.32
        env:
          MYSQL_ROOT_PASSWORD: test
          MYSQL_DATABASE: test
        ports:
          - 3336:3306

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Checkout project sources
        uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          build-root-directory: ./flower-shop
      - name: Run build with Gradle Wrapper
        run: cd ./flower-shop/ && ./gradlew build
        
        

